query adminWorkerOnboardingOverview($jobId: String!, $workerId: String!){
    adminWorkerOnboardingOverview(workerId: $workerId){
        companyOnboarding{
            companyId
            description
            id
            name
            onboardingPartsNumber
            referenceUrl
        }
        completedMessage
        id
        message
        onboardingParts{
            companyId
            companyOnboardingId
            confirmationMessage
            description
            failedMessage
            id
            integrationObject
            isEnabled
            name
            pendingMessage
            quizId
            referenceUrl
        }
        percentageCompleted
        state
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noJobMatches
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
    }
}