query appInit($jobId: String!, $workerId: String){
    appInit(workerId: $workerId){
        chatIntegrationSetting{
            active
            configuration
            provider
        }
        company{
            address
            addressState
            city
            country
            description
            id
            logoUrl
            mainContactEmail
            mainContactName
            name
            phone
            zip
        }
        companyConfig{
            adpUrl
            benefitUrls
            companyId
            contactSupportUrl
            defaultLocationImageMobileUrl
            defaultLocationImageThumbnailUrl
            defaultLocationImageWebUrl
            distanceUnit
            enableClickTracking
            enableScreenTracking
            facebookUrl
            faqsUrl
            id
            instagramUrl
            linkedInUrl
            linkedinRedirectUrl
            messagingServiceSender
            mobileOpusPolicies
            oneSignalAppId
            privacyPoblicyUrl
            privacyPolicyContent
            referalRewardContent
            reportBugsUrl
            termUrl
            twitterUrl
            usingModules
            webOpusPolicies
            webPortalUrl
            youtubeUrl
        }
        masterData
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noJobMatches
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
        workerOnboarding{
            companyOnboardingId
            currentPartIndex
            id
            message
            numOfCompletedSteps
            percentageCompleted
            permittedEvents
            state
        }
    }
}