query appWalkthroughs{
    appWalkthroughs{
        completed
        components{
            completed
            description
            id
            target
            title
        }
        id
        name
        webUrl
    }
}