query detailEmployer($size: [String!]!, $id: String!){
    detailEmployer(id: $id){
        agreedToTerms
        avatar{
            blobId
            contentType
            fileUrl
            filename
            id
            imageUrls(size: $size)
            thumbnails
        }
        changePasswordRequired
        client{
            address1
            address2
            city
            contactEmail
            contactFirstName
            contactLastName
            contactName
            contactPhone
            country
            description
            ein
            id
            latitude
            longitude
            name
            phone
            state
            status
            taxId
            url
            verifiedAt
            verifyStatus
            zipCode
        }
        company{
            address
            addressState
            city
            country
            description
            id
            logoUrl
            mainContactEmail
            mainContactName
            name
            phone
            zip
        }
        email
        firstName
        id
        intervieweesNumber
        lastName
        lastSignInAt
        paymentMethod
        permittedEvents
        phone
        scope
        scopesAreAllowedToUpdate
        status
        title
        totalUnreadMessage
    }
}