query employerListInterviews($filter: JobApplicantFilter, $limit: Int, $offset: Int, $sortBy: JobApplicantManagementSort){
    employerListInterviews(filter: $filter, limit: $limit, offset: $offset, sortBy: $sortBy){
        interviews{
            address1
            address2
            city
            createdAt
            description
            employerNote
            id
            interviewEndTime
            interviewLink
            interviewStartTime
            interviewType
            note
            state
            status
            statusName
            statusUpdatedAt
            timezone
            title
            updateEvents
            updatedAt
            zipCode
        }
        totalCount
    }
}