query employerListLocations($after: String, $before: String, $clientId: String, $first: Int, $last: Int, $nameContain: String, $status: LocationActiveEnum){
    employerListLocations(after: $after, before: $before, clientId: $clientId, first: $first, last: $last, nameContain: $nameContain, status: $status){
        edges{
            cursor
        }
        nodes{
            active
            address
            addressState
            city
            clientId
            companyId
            country
            distanceToCurrentUserSearchLocation
            id
            latitude
            longitude
            name
            phone
            region
            statusUpdatedAt
            zipcode
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageSize
            startCursor
        }
        totalCount
    }
}