query jobApplicants($filter: JobApplicantFilter, $limit: Int, $offset: Int, $sortBy: JobApplicantManagementSort){
    jobApplicants(filter: $filter, limit: $limit, offset: $offset, sortBy: $sortBy){
        jobApplicants{
            address
            address2
            applicationProcess
            applyDate
            city
            country
            createdAt
            discipline
            duration
            durationType
            employerNote
            frequency
            id
            isDirectOffer
            jobTitle
            latitude
            longitude
            minPayAmount
            note
            offerDate
            payAmount
            shifts
            source
            specialty
            startDate
            startedStatus
            startedStatusName
            state
            status
            statusName
            statusUpdatedAt
            timeOffEndDate
            timeOffStartDate
            updateEvents
            updatedAt
            zipcode
        }
        totalCount
    }
}