query messageThreads($jobId: String!, $filter: CompanyManagementFilter, $keywordSearch: String, $limit: Int, $offset: Int, $workerId: String){
    messageThreads(filter: $filter, keywordSearch: $keywordSearch, limit: $limit, offset: $offset, workerId: $workerId){
        client{
            address1
            address2
            city
            contactEmail
            contactFirstName
            contactLastName
            contactName
            contactPhone
            country
            description
            ein
            id
            latitude
            longitude
            name
            phone
            state
            status
            taxId
            url
            verifiedAt
            verifyStatus
            zipCode
        }
        clientId
        company{
            address
            addressState
            city
            country
            description
            id
            logoUrl
            mainContactEmail
            mainContactName
            name
            phone
            zip
        }
        companyId
        id
        lastMessage
        lastTenMessages{
            createdAt
            id
            message
            objectId
            objectType
            status
        }
        lastTimestamp
        objectId
        objectType
        threadIconUrl
        unreadMessageCounter
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noJobMatches
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
    }
}