query notifications($after: String, $before: String, $events: [String!], $exceptEvents: [String!], $first: Int, $last: Int){
    notifications(after: $after, before: $before, events: $events, exceptEvents: $exceptEvents, first: $first, last: $last){
        edges{
            cursor
        }
        nodes{
            createdAt
            dataEvent
            dataId
            dataType
            heading
            id
            message
            status
            updatedAt
            url
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageSize
            startCursor
        }
        totalCount
        totalRead
        totalUnread
    }
}