query popularCities{
    popularCities{
        availableJobs
        avgWeeklyRate
        city
        cityImage
        highWeeklyRate
        locationImage{
            city
            id
            state
        }
        lowWeeklyRate
        state
        totalJobs
    }
}