query workerToken($jobId: String!, $token: String!){
    workerToken(token: $token){
        notificationChannel
        token
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noJobMatches
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
    }
}