query workerAssignment($jobId: String!, $id: String){
    workerAssignment(id: $id){
        address
        address2
        availableToExtend
        city
        client{
            address1
            address2
            city
            contactEmail
            contactFirstName
            contactLastName
            contactName
            contactPhone
            country
            description
            ein
            id
            latitude
            longitude
            name
            phone
            state
            status
            taxId
            url
            verifiedAt
            verifyStatus
            zipCode
        }
        country
        createdAt
        currentWorkWeek{
            active
            endDate
            id
            startDate
        }
        discipline
        duration
        durationType
        endDate
        frequency
        id
        job{
            address
            address2
            applicantCount
            benefitContent
            canApply
            city
            complianceRequirements
            country
            createdAt
            createdDate
            customStartDate
            description
            discipline
            distance
            distanceToCurrentUserSearchLocation
            draftId
            duration
            durationType
            employerOfRecord
            exclusiveJob
            externalCreatedAt
            externalJobId
            externalUpdatedAt
            facilityType
            favoriteCount
            frequency
            hospital
            hoursPerWeek
            id
            images
            isAsap
            isBookmarked
            isDisliked
            isFavorited
            isLiked
            isSkillChecklist
            jobType
            latitude
            longitude
            matchingPercentage
            minExpYear
            minWeeklyPayAmount
            noTalentMatches
            profileRequirements
            publishedAt
            requirementNotes
            shifts
            skillId
            skillLongName
            skillName
            slotsNumber
            slug
            specialty
            startDate
            state
            status
            templateName
            title
            topWorkerMatchingScores
            updatedAt
            viewCount
            weeklyPayAmount
            zipcode
        }
        jobApplicant{
            address
            address2
            applicationProcess
            applyDate
            city
            country
            createdAt
            discipline
            duration
            durationType
            employerNote
            frequency
            id
            isDirectOffer
            jobTitle
            latitude
            longitude
            minPayAmount
            note
            offerDate
            payAmount
            shifts
            source
            specialty
            startDate
            startedStatus
            startedStatusName
            state
            status
            statusName
            statusUpdatedAt
            timeOffEndDate
            timeOffStartDate
            updateEvents
            updatedAt
            zipcode
        }
        jobTitle
        latitude
        longitude
        minPayAmount
        payAmount
        previousWorkWeek{
            active
            endDate
            id
            startDate
        }
        shifts
        specialty
        startDate
        state
        status
        updatedAt
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
        zipcode
    }
}