query workedTimecards($size: [String!]!, $after: String, $before: String, $first: Int, $last: Int){
    workedTimecards(after: $after, before: $before, first: $first, last: $last){
        edges{
            cursor
        }
        nodes{
            blobId
            contentType
            fileUrl
            filename
            id
            imageUrls(size: $size)
            thumbnails
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageSize
            startCursor
        }
        totalCount
    }
}