query workerCertifications($size: [String!]!, $jobId: String!, $workerId: String!){
    workerCertifications(workerId: $workerId){
        certificationType
        compactLicense
        company{
            address
            addressState
            city
            country
            description
            id
            logoUrl
            mainContactEmail
            mainContactName
            name
            phone
            zip
        }
        createdAt
        expirationDate
        id
        licenseDiscipline
        licenseImages{
            blobId
            contentType
            fileUrl
            filename
            id
            imageUrls(size: $size)
            thumbnails
        }
        licenseNumber
        licenseState
        title
        worker{
            agreedToTerms
            availableStartDate
            avatarUrl
            blocked
            changePasswordRequired
            completedJobsNumber
            dateOfBirth
            email
            employmentType
            facilityTypes
            firstName
            hasActiveAssignment
            id
            isFavorited
            jobCategoriesWorkedNumber
            jobMatchingScore(jobId: $jobId)
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noJobMatches
            noNotification
            noSms
            noTalentMatches
            overallRating
            phone
            phoneVerifiedAt
            profilePercentageCompleted
            referralCode
            referralMethod
            referrerCode
            remainingExpirationTime
            shiftRequested
            socialSecurityNumber
            timeOffRequested
            totalUnreadMessage
            workAuthorized
        }
    }
}