query worker($id: String){
    worker(id: $id){
        agreedToTerms
        availableStartDate
        changePasswordRequired
        company{
            address
            addressState
            city
            country
            description
            id
            logoUrl
            mainContactEmail
            mainContactName
            name
            phone
            zip
        }
        completedJobsNumber
        email
        facilityTypes
        firstName
        id
        jobCategoriesWorkedNumber
        lastName
        lastOtpExpiredAt
        lastSignInAt
        locationsWorkedNumber
        maidenName
        noCall
        noEmail
        noNotification
        noSms
        notificationSetting{
            assignmentEndingReminder
            completeOnboarding
            documentExpired
            id
            jobAlert
            jobsRecommendation
            licenseExpired
            licenseExpiredOptions
            licenseWillBeExpiredOptions
            timecardSubmissionReminder
        }
        overallRating
        phone
        phoneVerifiedAt
        recruiter{
            companyId
            email
            id
            name
            phone
            title
        }
        referralCode
        referralMethod
        referrerCode
        shiftRequested
        timeOffRequested
        workAuthorized
        workExperienceOverview{
            discipline
            id
            primarySpecialty
            secondarySpecialty
            yearsOfExperience
        }
        workExperiences{
            agency
            assignmentType
            bedsInUnit
            birthsPerMonth
            chartingSoftwareUsed
            city
            country
            currentlyEmployed
            dailyCensus
            dutiesPerformed
            endDate
            facilityName
            facilityType
            floatSpecialty
            id
            mayContactSupervisor
            numberSuites
            nurseRatio
            patientRatio
            patientType
            position
            reasonForLeaving
            startDate
            state
            supervisor
            travelAssignment
            unitSpecialty
            zipcode
        }
        workedTimesheets{
            callHours
            id
            paidHours
            shiftsWorked
            status
        }
        workerAddress{
            aptNumber
            city
            country
            id
            state
            street
            workerId
            zipcode
        }
        workingPreferredLocations{
            id
            preferredWorkingCity
            preferredWorkingState
        }
    }
}