query jobSearch($filter: JobFilter, $limit: Int, $offset: Int, $sortBy: JobManagementSort){
    jobSearch(filter: $filter, limit: $limit, offset: $offset, sortBy: $sortBy){
        jobs{
            createdAt
            createdDate
            customStartDate
            distance
            duration
            exclusiveJob
            externalCreatedAt
            externalUpdatedAt
            facilityType
            favoriteCount
            frequency
            hoursPerWeek
            id
            images
            jobType
            matchingPercentage
            minWeeklyPayAmount
            shifts
            slotsNumber
            slug
            startDate
            status
            title
            updatedAt
            viewCount
            weeklyPayAmount
        }
        totalCount
    }
}