query workerEducations($workerId: String){
    workerEducations(workerId: $workerId){
        city
        country
        createdAt
        degreeDate
        degreeName
        id
        major
        schoolName
        state
        worker{
            agreedToTerms
            availableStartDate
            changePasswordRequired
            completedJobsNumber
            email
            facilityTypes
            firstName
            id
            jobCategoriesWorkedNumber
            lastName
            lastOtpExpiredAt
            lastSignInAt
            locationsWorkedNumber
            maidenName
            noCall
            noEmail
            noNotification
            noSms
            overallRating
            phone
            phoneVerifiedAt
            referralCode
            referralMethod
            referrerCode
            shiftRequested
            timeOffRequested
            workAuthorized
        }
    }
}